version: "2"
services:
  api:
    build: .
    volumes:
      - ./:/usr/src/app/
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
  mongo: 
    image: mongo
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
    - mongo